# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTTP-Request-FromTemplate
version:      0.01
version_from: lib/HTTP/Request/FromTemplate.pm
installdirs:  site
requires:
    HTTP::Message:                 0
    HTTP::Request:                 0
    Template:                      0
    Test::Base:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
