--- #YAML:1.0
name:                HTTP-Request-FromTemplate
version:             0.03
abstract:            Create HTTP requests from templates
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Class::Accessor:               0
    HTTP::Message:                 0
    HTTP::Request:                 0
    Template:                      0
    Test::Base:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Max Maischein <corion@cpan.org>
